GET  http://localhost:5213/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjIiLCJlbWFpbCI6IjEyMyIsInN1YiI6IjEyMyIsImp0aSI6IjljZmVjMTBhLWE4Y2YtNGI2Zi04Y2UzLTcwOWQ3ZGE3MTNjMiIsIm5iZiI6MTcxMjkyNjQwNCwiZXhwIjoxNzEzNTMxMjA0LCJpYXQiOjE3MTI5MjY0MDR9.jkVa8Ux64PkSXS0lF0HFHxh_qM9TXswncBOgiQdp1_8
Accept: application/json
Content-Type: application/json

