export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";


export const FETCH_QUIZ_CATEGORIES_REQUEST = "FETCH_QUIZ_CATEGORIES_REQUEST";
export const FETCH_QUIZ_CATEGORIES_SUCCESS = "FETCH_QUIZ_CATEGORIES_SUCCESS";
export const FETCH_QUIZ_CATEGORIES_FAILURE = "FETCH_QUIZ_CATEGORIES_FAILURE";

export const FETCH_TYPES_REQUEST = "FETCH_TYPES_REQUEST";
export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";
export const FETCH_TYPES_FAILURE = "FETCH_TYPES_FAILURE";

export const FETCH_DIFFICULTY_REQUEST = "FETCH_DIFFICULTY_REQUEST";
export const FETCH_DIFFICULTY_SUCCESS = "FETCH_DIFFICULTY_SUCCESS";
export const FETCH_DIFFICULTY_FAILURE = "FETCH_DIFFICULTY_FAILURE";

export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";

export const SET_QUIZ_QUESTIONS = "SET_QUIZ_QUESTIONS";
export const SET_QUIZ_CATEGORY = "SET_QUIZ_CATEGORY";
export const SET_QUIZ_TYPE = "SET_QUIZ_TYPE";
export const SET_QUIZ_DIFFICULTY = "SET_QUIZ_DIFFICULTY";
export const SET_QUIZ_SELECTED_ANSWERS = "SET_QUIZ_SELECTED_ANSWERS";
export const CLEAR_QUIZ = "CLEAR_QUIZ";

export const ADD_QUIZ_REQUEST = "ADD_QUIZ_REQUEST";
export const ADD_QUIZ_SUCCESS = "ADD_QUIZ_SUCCESS";
export const ADD_QUIZ_FAILURE = "ADD_QUIZ_FAILURE";

export const FETCH_HISTORY_REQUEST = "FETCH_HISTORY_REQUEST";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_HISTORY_FAILURE = "FETCH_HISTORY_FAILURE";
